### ISSUE TITLE
Conflicts with serverside commands

### ISSUE THREAD

**Issue by o7Moon** [LualtOfficial/qol-core#1]
To prevent client-side commands from blocking server-side ones, there should be a configurable prefix (that defaults to something other than "/" since multiple server-side mods use it already).

**Comment by o7Moon** [comment]
also before I forget: command help messages should use the custom prefix as well. either by replacing "/" with the prefix or by having another special keyword which gets replaced with the prefix.

**Comment by Lualttt** [comment]
i already wanted to add this so ill try to get this added asap

**Comment by Lualttt** [comment]
added, use `/prefix prefix-here` or go into the config to change it
