### ISSUE TITLE
Command namespacing

### ISSUE THREAD

**Issue by o7Moon** [LualtOfficial/qol-core#2]
if two different mods (`ModA` and `ModB`) register a command with the same name (`/cmd`), whichever is registered last would be the one that gets ran. In order to allow running either command, it should be possible to specify which mod a command is from, so that `/ModA:cmd` and `/ModB:cmd` can be ran.

I think it would make sense if:
- `RegisterMod(...)` returned the new `Mod` object
- `RegisterCommand(...)` took an optional `Mod` parameter 
- There is a warning logged if a command is registered without a `Mod`, saying that it is possible that the command might be overridden and inaccessible if a `Mod` is not provided.

**Comment by Lualttt** [comment]
hadn't even thought of this ill def be looking into it :+1:

**Comment by Lualttt** [comment]
added, but the mod parameter is required
